### ISSUE TITLE
bwa-mem.json example: Image not found.

### ISSUE THREAD

**Issue by jeremiahsavage** [rabix/rabix#131]
I'm attempting to run the "Basic usage" example given https://github.com/rabix/rabix
but I'm not able to pull the docker image. Is there a working example that does load a docker image? I've tried to pull from quay.io, but am not able to, so I would like to start with a working example. Thanks.
```
$ rabix -v https://s3.amazonaws.com/rabix/rabix-test/bwa-mem.json -- \
>  --reference https://s3.amazonaws.com/rabix/rabix-test/chr20.fa \
>  --reads https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_1.fastq \
>  --reads https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_2.fastq
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:rabix.common.io:Fetched metadata from https://s3.amazonaws.com/rabix/rabix-test/chr20.fa.rbx.json
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:rabix.common.io:Fetched metadata from https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_1.fastq.rbx.json
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:rabix.common.io:Fetched metadata from https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_2.fastq.rbx.json
INFO:rabix.docker.container:Pulling images.sbgenomics.com/rabix/bwa
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): images.sbgenomics.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): images.sbgenomics.com
Unable to load "images.sbgenomics.com/rabix/bwa". Image not found.

```

**Comment by StarvingMarvin** [comment]
Hi!

Thanks for heads up. I seams we've misplaced the image in the meanwhile, but things should be fixed now. Please try again.

Cheers,
Luka

**Comment by jeremiahsavage** [comment]
Hello! I'm still getting the error on two different machines
```
$ rabix -v https://s3.amazonaws.com/rabix/rabix-test/bwa-mem.json -- \
>  --reference https://s3.amazonaws.com/rabix/rabix-test/chr20.fa \
>  --reads https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_1.fastq \
>  --reads https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_2.fastq
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:rabix.common.io:Fetched metadata from https://s3.amazonaws.com/rabix/rabix-test/chr20.fa.rbx.json
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:rabix.common.io:Fetched metadata from https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_1.fastq.rbx.json
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
INFO:rabix.common.io:Fetched metadata from https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_2.fastq.rbx.json
INFO:rabix.docker.container:Pulling images.sbgenomics.com/rabix/bwa
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): images.sbgenomics.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): images.sbgenomics.com
Unable to load "images.sbgenomics.com/rabix/bwa". Image not found.
```

**Comment by StarvingMarvin** [comment]
What's your docker version?

Unfortunately, referenced image is hosted on v1 docker registry, so the latest docker version that can communicate with it is 1.6. You can try out this example with attached json that targets official docker registry. You can save it somewhere and than try out this example with:

|rabix -v bwa-mem.json -- \
  --reference https://s3.amazonaws.com/rabix/rabix-test/chr20.fa \
  --reads https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_1.fastq \
  --reads https://s3.amazonaws.com/rabix/rabix-test/example_human_Illumina.pe_2.fastq|



Cheers.
Luka

**Comment by StarvingMarvin** [comment]
Github ate attachment. Here it is:
[bwa-mem.json.txt](https://github.com/rabix/rabix/files/25479/bwa-mem.json.txt)

**Comment by jeremiahsavage** [comment]
Thank you. Version incompatibility was the problem, and the example now works perfectly.
```
$ docker --version
Docker version 1.7.1, build 786b29d
```
